#!/bin/bash

#root -l -q -b 'check_strips.cc(12,0,"3B")'
#root -l -q -b 'check_strips.cc(13,0,"0B")'
#root -l -q -b 'check_strips.cc(14,0,"1B")'
#root -l -q -b 'check_strips.cc(15,0,"2B")'
#root -l -q -b 'check_strips.cc(16,0,"0A")'
#root -l -q -b 'check_strips.cc(17,0,"1A")'
#root -l -q -b 'check_strips.cc(18,0,"2A")'
#root -l -q -b 'check_strips.cc(19,0,"3A")'
#root -l -q -b 'check_strips.cc(20,1,"0A")'
#root -l -q -b 'check_strips.cc(21,1,"1A")'
#root -l -q -b 'check_strips.cc(22,1,"2A")'
#root -l -q -b 'check_strips.cc(23,1,"3A")'
#root -l -q -b 'check_strips.cc(24,1,"0B")'
#root -l -q -b 'check_strips.cc(25,1,"1B")'
#root -l -q -b 'check_strips.cc(26,1,"2B")'
#root -l -q -b 'check_strips.cc(27,1,"3B")'
#root -l -q -b 'check_strips.cc(28,2,"0A")'
#root -l -q -b 'check_strips.cc(29,2,"1A")'
#root -l -q -b 'check_strips.cc(30,2,"2A")'
#root -l -q -b 'check_strips.cc(31,2,"3A")'
#root -l -q -b 'check_strips.cc(32,2,"0B")'
root -l -q -b 'check_strips.cc(33,2,"1B")'
root -l -q -b 'check_strips.cc(34,2,"1B")'
root -l -q -b 'check_strips.cc(35,2,"2B")'
root -l -q -b 'check_strips.cc(36,2,"3B")'
root -l -q -b 'check_strips.cc(37,2,"2B")'
