#if defined (__MAKECINT__) || (__CLING__)
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link off all typedef;
#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;
#pragma link C++ class TIssData;
#pragma link C++ class ISSCalibration+;
#pragma link C++ class ISSSettings+;
//#pragma link C++ class CommandLineInterface;
#pragma link C++ class ISSConverter+;
#pragma link C++ class ISSEventBuilder+;
#pragma link C++ class ISSEvts+;
#pragma link C++ class ISSArrayEvt+;
#pragma link C++ class ISSArrayPEvt+;
#pragma link C++ class ISSRecoilEvt+;
#pragma link C++ class ISSMwpcEvt+;
#pragma link C++ class ISSElumEvt+;
#pragma link C++ class ISSZeroDegreeEvt+;
#pragma link C++ class ISSGammaRayEvt+;
#pragma link C++ class ISSLumeEvt+;
#pragma link C++ class ISSCDEvt+;
#pragma link C++ class ISSDataPackets+;
#pragma link C++ class ISSAsicData+;
#pragma link C++ class ISSVmeData+;
#pragma link C++ class ISSCaenData+;
#pragma link C++ class ISSMesyData+;
#pragma link C++ class ISSInfoData+;
#pragma link C++ class ISSReaction+;
#pragma link C++ class ISSParticle+;
#pragma link C++ class ISSRxEvent+;
#pragma link C++ class ISSRxInfo+;
#pragma link C++ class ISSGUI;
#pragma link C++ class ISSDialog;
#endif
